id: AB3B124BB
title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness the Dalai
  Lama'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.072079
  last_modified_at: 2022-02-28 23:18:37.072085
