id: AB3B124BB
title: A Prayer to Kindle the Three Faiths, Addressed to the Seventeen Great Paṇḍitas
  of Glorious Nālandā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.037515
  last_modified_at: 2022-02-28 23:18:37.037524
