id: AB3B124BB
title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate Teacher
  Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.039775
  last_modified_at: 2022-02-28 23:18:37.039778
