id: AB3B124BB
title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong Trulshik
  Rinpoche, the Representative of Guru Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.044411
  last_modified_at: 2022-02-28 23:18:37.044414
