id: AB3B124BB
title: Prayer to His Holiness the Dalai Lama
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.058276
  last_modified_at: 2022-02-28 23:18:37.058278
