id: AB3B124BB
title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for the ''Neck-Pouch
  Dagger’ (Purba Gulkhukma) Cycle'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.042483
  last_modified_at: 2022-02-28 23:18:37.042486
