id: AB3B124BB
title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the Enlightened
  Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton Lerab Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.083575
  last_modified_at: 2022-02-28 23:18:37.083588
