id: AB3B124BB
title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life of His
  Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One by Jamyang
  Khyentse Chökyi Lodrö'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.066856
  last_modified_at: 2022-02-28 23:18:37.066887
