id: AB3B124BB
title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind Kīla
  Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.085938
  last_modified_at: 2022-02-28 23:18:37.085943
