id: AB3B124BB
title: Prayer for the Long Life of Dzogchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - es
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.051832
  last_modified_at: 2022-02-28 23:18:37.051839
