id: AB3B124BB
title: The Prayer of the Words of Truth
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.075370
  last_modified_at: 2022-02-28 23:18:37.075373
