id: AB3B124BB
title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life of Ḍākinī
  Muntso Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.060179
  last_modified_at: 2022-02-28 23:18:37.060182
