id: AB3B124BB
title: Aspiration Prayer for the Flourishing of the Jonang Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.041323
  last_modified_at: 2022-02-28 23:18:37.041326
