id: AB3B124BB
title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His Holiness
  the Dalai Lama'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.061739
  last_modified_at: 2022-02-28 23:18:37.061742
