id: AB3B124BB
title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of the
  Non-Sectarian Teachings of the Buddha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:18:37.080880
  last_modified_at: 2022-02-28 23:18:37.080884
